import './app-body.html';
import './app-body.js';
import './app-not-found.html';
import './cas-login.html';
import './cas-login.js';
import './footer.html';
import './header.html';
import './header.js';
import './if-logged-in.html';
import './if-logged-in.js';
import './loading.html';
import './welcome-banner.html';
import './homepage-body.html';
import './homepage-body.js';
import './suggested-projects.html';
import './suggested-projects.js';
import './loggedin-body.html';
import './loggedin-menu.html'
import './member_dropdown.html'
import './member_dropdown'